In [23]:
from PIL import Image # image open
import os # iterate on elements of a folder
import numpy as np

In [24]:
# read the image dataset
dog_imgs = []
psize = 256
for filename in os.listdir(r'./Images/Yorkshire_terrier'): # iterate on filenames
    if filename.endswith(".jpg") or filename.endswith(".png"):
        img = Image.open('./Images/Yorkshire_terrier/' + filename)
        img = np.array(img.resize((psize,psize))).astype(np.float32).reshape(psize,psize,3) # w x h x rgb
        dog_imgs.append(img)
dog_imgs = np.asarray(dog_imgs)
# standard scale
mean, std = dog_imgs.mean(), dog_imgs.std()
dog_imgs = (dog_imgs - mean) / std

In [25]:
dog_imgs

array([[[[-1.4250629 , -1.4250629 , -1.4250629 ],
         [-1.4250629 , -1.4250629 , -1.4250629 ],
         [-1.4250629 , -1.4250629 , -1.4250629 ],
         ...,
         [-1.3519564 , -1.381199  , -1.3373351 ],
         [-1.3519564 , -1.381199  , -1.3373351 ],
         [-1.3519564 , -1.381199  , -1.3373351 ]],

        [[-1.4250629 , -1.4250629 , -1.4250629 ],
         [-1.4250629 , -1.4250629 , -1.4250629 ],
         [-1.4250629 , -1.4250629 , -1.4250629 ],
         ...,
         [-1.3519564 , -1.381199  , -1.3373351 ],
         [-1.3519564 , -1.381199  , -1.3373351 ],
         [-1.3519564 , -1.381199  , -1.3373351 ]],

        [[-1.4250629 , -1.4250629 , -1.4250629 ],
         [-1.4250629 , -1.4250629 , -1.4250629 ],
         [-1.4250629 , -1.4250629 , -1.4250629 ],
         ...,
         [-1.3519564 , -1.381199  , -1.3373351 ],
         [-1.3519564 , -1.381199  , -1.3373351 ],
         [-1.3519564 , -1.381199  , -1.3373351 ]],

        ...,

        [[-1.3519564 , -1.381199  , -1

In [26]:
# split to train-validation-test dataset
test_split = 0.1
valid_split = 0.1
v_index= int(dog_imgs.shape[0]*(1-valid_split-test_split))
t_index= int(dog_imgs.shape[0]*(1-test_split))

dog_imgs_test = dog_imgs[t_index:]
dog_imgs_valid = dog_imgs[v_index:t_index]
dog_imgs_train = dog_imgs[:v_index]

In [31]:
dog_imgs.shape

(164, 256, 256, 3)

In [33]:
dog_imgs_test.shape

(17, 256, 256, 3)

In [34]:
dog_imgs_test

array([[[[ 1.7477609 ,  1.6892756 ,  1.557684  ],
         [ 1.7623823 ,  1.703897  ,  1.5723052 ],
         [ 1.7770035 ,  1.7185183 ,  1.557684  ],
         ...,
         [-1.001045  , -0.88407457, -1.191122  ],
         [-1.0595303 , -1.0156664 , -1.1765007 ],
         [-0.88407457, -0.8402106 , -1.001045  ]],

        [[ 1.7477609 ,  1.6892756 ,  1.557684  ],
         [ 1.7477609 ,  1.6892756 ,  1.557684  ],
         [ 1.7770035 ,  1.7185183 ,  1.557684  ],
         ...,
         [-1.0156664 , -0.91331714, -1.1765007 ],
         [-1.1765007 , -1.1326368 , -1.2642286 ],
         [ 0.18328094,  0.22714487,  0.09555309]],

        [[ 1.7331396 ,  1.6746544 ,  1.5430626 ],
         [ 1.7477609 ,  1.6892756 ,  1.557684  ],
         [ 1.7770035 ,  1.7185183 ,  1.557684  ],
         ...,
         [-1.0156664 , -0.91331714, -1.1765007 ],
         [-1.0156664 , -0.9718024 , -1.0741515 ],
         [ 0.7681333 ,  0.8119972 ,  0.709648  ]],

        ...,

        [[ 1.9817017 ,  1.9378378 ,  1

In [91]:
from scipy.io import wavfile
# read the sound dataset
dog_barkings = []
for filename in os.listdir(r'./Sounds/dog_barking'): # iterate on filenames
    if filename.endswith(".wav"):
        samp_rate, data = wavfile.read('./Sounds/dog_barking/' + filename)
        dog_barkings.append(data)
dog_barkings = np.asarray(dog_barkings)

In [96]:
# standard scale
mean, std = np.hstack(dog_barkings).mean(), np.hstack(dog_barkings).std()
dog_barkings = (dog_barkings - mean) / std

In [97]:
# split to train-validation-test dataset
test_split = 0.1
valid_split = 0.1
v_index= int(dog_barkings.shape[0]*(1-valid_split-test_split))
t_index= int(dog_barkings.shape[0]*(1-test_split))

dog_barkings_test = dog_barkings[t_index:]
dog_barkings_valid = dog_barkings[v_index:t_index]
dog_barkings_train = dog_barkings[:v_index]

In [98]:
dog_barkings_test.shape

(12,)

In [99]:
dog_barkings.shape

(113,)

In [100]:
dog_barkings

array([array([-0.00441412, -0.00463319, -0.00419504, ..., -0.00025165,
        0.00259635,  0.00653973]),
       array([ 0.01793174,  0.00347266, -0.01251996, ..., -0.08306275,
       -0.10869476, -0.10738029]),
       array([-0.00244242, -0.06663198, -0.08897783, ..., -0.04976305,
       -0.06575567, -0.06159321]),
       array([ 0.03830589,  0.04334467,  0.08343575, ..., -0.14462338,
       -0.13345046, -0.1187723 ]),
       array([ 0.03195266,  0.05517482,  0.05166959, ..., -0.07670952,
       -0.08109106, -0.05173474]),
       array([0.01968435, 0.04246836, 0.02888558, ..., 0.07270098, 0.06087082,
       0.02669481]),
       array([-0.00660489, -0.00200427, -0.00923381, ..., -0.01471073,
       -0.01799689, -0.02763628]),
       array([ 0.01683635,  0.0135502 , -0.01733966, ..., -0.02610274,
       -0.01295812, -0.01624427]),
       array([-0.00156612, -0.00156612, -0.00156612, ...,  0.1029336 ,
        0.1419293 ,  0.14039577]),
       array([-0.01142458, -0.01624427, -0.01843504,